version: "2"

services:
  loraserver:
    image: loraserver/loraserver:2
    volumes:
      - ./configuration/loraserver:/etc/loraserver
    networks:
      - back

  appserver:
    image: loraserver/lora-app-server:2
    ports:
      - 8080:8080
    volumes:
      - ./configuration/lora-app-server:/etc/lora-app-server
    networks:
      - proxy-network
      - back
    environment:
      - VIRTUAL_PROTO=https
      - VIRTUA_PORT=443
      - VIRTUAL_HOST=loraserver.${DOMAIN}

  gatewaybridge:
    image: loraserver/gatewaybridge
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/lora-gateway-bridge:/etc/lora-gateway-bridge
    networks:
      - back

  geoserver:
    image: loraserver/lora-geo-server:2
    volumes:
      - ./configuration/lora-geo-server:/etc/lora-geo-server

  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - back

  redis:
    image: redis:4-alpine
    volumes:
      - ./data/redis:/data
    networks:
      - back

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    networks:
      - back

networks:
  proxy-network:
    external:
      name: proxy-network
  back:
    driver: bridge
